### ISSUE TITLE
[feat] 감정 날씨 통계 클릭 시 나타나는 텍스트 박스 구현 

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#144]
## ISSUE
- 감정 날씨 통계 클릭 시 나타나는 텍스트 박스 구현 

## To-do
- [x] 감정 날씨 통계 클릭 시 나타나는 텍스트 박스 구현 
- [x] 각 날씨 bar 클릭 시 화면에 나타나도록 구현

**Comment by yeriinnn** [comment]
메인에 merge완료
