### ISSUE TITLE
[feat] 비교분석내 화살표 파일 수정

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#152]
## ISSUE
- 비교분석내 화살표 파일 수정

## To-do
- [x] 비교분석내 화살표 디자인 수정 - 더 이상 이전/이후 로 넘어갈 수 없을 때 회색 화살표 파일 

## 참고사항 및 체크포인트
기능 구현 시 같이 추가할 예정이었으나, 시연 영상 찍을 때까지 시간이 촉박해서 우선 보여지는 것만 수정합니다...!

**Comment by yeriinnn** [comment]
메인에 merge완료
