### ISSUE TITLE
[setting] 비교분석뷰 내 data class 파일 옮김

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#177]
## ISSUE
- 비교분석뷰 내 data class 파일 옮김

## To-do
- [x] 비교분석뷰 내 data class 파일 옮김

## 참고사항 및 체크포인트
data 패키지에 있던 data class 를 data > entity 패키지로 옮김

**Comment by yeriinnn** [comment]
메인에 merge완료
