### ISSUE TITLE
[add]캘린더 상세보기 저장 버튼 기능 구현

### ISSUE THREAD

**Issue by hyemyu** [yourweather/yourweather_android#254]
## ISSUE
- 캘린더 상세보기 저장 버튼 기능 구현

## To-do
- [x] 캘린더 상세보기 저장 버튼 색상 기능 구현
- [x]날씨버튼, seekbar버튼 입력값 저장 기능 구현

**Comment by yeriinnn** [comment]
메인에 머지완료
