### ISSUE TITLE
[feat] 미입력 내역 존재 시, 미존재 시 화면 전환, 미입력 리스트 보여주기 구현

### ISSUE THREAD

**Issue by kangyuri1114** [yourweather/yourweather_android#264]
## ISSUE
-  미입력 내역 존재 시, 미존재 시 화면 전환, 미입력 리스트 보여주기 구현

## To-do
- [x]  미입력 내역 존재 시, 미존재 시 화면 전환, 종 우측 상단 알림 표시 나오게
- [x] 미입력 리스트 존재 시 리스트 보여주기

**Comment by yeriinnn** [comment]
메인에 머지완료
