### ISSUE TITLE
[setting]맡은 부분 presentation 내에 폴더 생성해서 묶기

### ISSUE THREAD

**Issue by ParkSeojin1101** [yourweather/yourweather_android#85]
## ISSUE
- presentation내에 각각 calendar, sign으로 디렉토리 생성해서 작업물 옮기기

## To-do
- [x] calendar 디렉 생성
- [x] sign 디렉 생성
- [x] 작업물 옮기기

**Comment by yeriinnn** [comment]
메인에 머지완료.
